# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - pair:
              elixir: "1.13"
              otp: "24.3.4.10"
          - pair:
              elixir: "1.15"
              otp: "26.0"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@main
        with:
          elixir-version: ${{ matrix.pair.elixir }}
          otp-version: ${{ matrix.pair.otp }}

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: mix-otp-${{ matrix.pair.otp }}-deps-${{ hashFiles('**/mix.lock') }}

      - name: Install dependencies
        run: mix deps.get

      - run: mix format --check-formatted

      - run: mix deps.unlock --check-unused

      - run: mix deps.compile

      - run: mix compile --warnings-as-errors

      - name: Run tests
        run: mix test --warnings-as-errors
